// <auto-generated />
using BuildingExample.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BuildingExample.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuildingExample.Models.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApartmentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Area")
                        .HasColumnType("double precision");

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfRooms")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApartmentNumber = "101",
                            Area = 50.0,
                            BuildingId = 1,
                            Floor = 1,
                            NumberOfRooms = 2
                        },
                        new
                        {
                            Id = 2,
                            ApartmentNumber = "102",
                            Area = 55.0,
                            BuildingId = 1,
                            Floor = 1,
                            NumberOfRooms = 2
                        },
                        new
                        {
                            Id = 3,
                            ApartmentNumber = "201",
                            Area = 60.0,
                            BuildingId = 1,
                            Floor = 2,
                            NumberOfRooms = 3
                        },
                        new
                        {
                            Id = 4,
                            ApartmentNumber = "202",
                            Area = 65.0,
                            BuildingId = 1,
                            Floor = 2,
                            NumberOfRooms = 3
                        },
                        new
                        {
                            Id = 5,
                            ApartmentNumber = "301",
                            Area = 70.0,
                            BuildingId = 2,
                            Floor = 3,
                            NumberOfRooms = 3
                        },
                        new
                        {
                            Id = 6,
                            ApartmentNumber = "302",
                            Area = 75.0,
                            BuildingId = 2,
                            Floor = 3,
                            NumberOfRooms = 3
                        },
                        new
                        {
                            Id = 7,
                            ApartmentNumber = "401",
                            Area = 80.0,
                            BuildingId = 3,
                            Floor = 4,
                            NumberOfRooms = 4
                        },
                        new
                        {
                            Id = 8,
                            ApartmentNumber = "402",
                            Area = 85.0,
                            BuildingId = 3,
                            Floor = 4,
                            NumberOfRooms = 4
                        },
                        new
                        {
                            Id = 9,
                            ApartmentNumber = "501",
                            Area = 90.0,
                            BuildingId = 4,
                            Floor = 5,
                            NumberOfRooms = 5
                        },
                        new
                        {
                            Id = 10,
                            ApartmentNumber = "502",
                            Area = 95.0,
                            BuildingId = 4,
                            Floor = 5,
                            NumberOfRooms = 5
                        },
                        new
                        {
                            Id = 11,
                            ApartmentNumber = "601",
                            Area = 100.0,
                            BuildingId = 5,
                            Floor = 6,
                            NumberOfRooms = 6
                        },
                        new
                        {
                            Id = 12,
                            ApartmentNumber = "602",
                            Area = 105.0,
                            BuildingId = 5,
                            Floor = 6,
                            NumberOfRooms = 6
                        });
                });

            modelBuilder.Entity("BuildingExample.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Floors")
                        .HasColumnType("integer");

                    b.Property<bool>("HasElevator")
                        .HasColumnType("boolean");

                    b.Property<int>("YearOfConstruction")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            Floors = 5,
                            HasElevator = true,
                            YearOfConstruction = 2000
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Ave",
                            Floors = 6,
                            HasElevator = false,
                            YearOfConstruction = 1995
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine Blvd",
                            Floors = 4,
                            HasElevator = true,
                            YearOfConstruction = 2010
                        },
                        new
                        {
                            Id = 4,
                            Address = "101 Maple Dr",
                            Floors = 8,
                            HasElevator = true,
                            YearOfConstruction = 2005
                        },
                        new
                        {
                            Id = 5,
                            Address = "202 Birch Rd",
                            Floors = 3,
                            HasElevator = false,
                            YearOfConstruction = 1990
                        });
                });

            modelBuilder.Entity("BuildingExample.Models.Apartment", b =>
                {
                    b.HasOne("BuildingExample.Models.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });
#pragma warning restore 612, 618
        }
    }
}
